# Generated by Django 3.1.7 on 2021-04-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20210415_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='summary',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
