# Generated by Django 3.1.7 on 2021-04-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_auto_20210419_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
    ]
