# Generated by Django 3.1.7 on 2021-04-21 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_auto_20210421_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
