# Generated by Django 3.1.7 on 2021-04-23 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_auto_20210421_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='summary',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='marketplace.order'),
        ),
    ]
